"""Build the embedded Korean bitmap subset and a review contact sheet."""
from __future__ import annotations

import ctypes
import re
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
W, H = 12, 12


class BITMAPINFOHEADER(ctypes.Structure):
    _fields_ = [
        ("biSize", ctypes.c_uint32), ("biWidth", ctypes.c_int32),
        ("biHeight", ctypes.c_int32), ("biPlanes", ctypes.c_uint16),
        ("biBitCount", ctypes.c_uint16), ("biCompression", ctypes.c_uint32),
        ("biSizeImage", ctypes.c_uint32), ("biXPelsPerMeter", ctypes.c_int32),
        ("biYPelsPerMeter", ctypes.c_int32), ("biClrUsed", ctypes.c_uint32),
        ("biClrImportant", ctypes.c_uint32),
    ]


class RGBQUAD(ctypes.Structure):
    _fields_ = [("b", ctypes.c_ubyte), ("g", ctypes.c_ubyte),
                ("r", ctypes.c_ubyte), ("a", ctypes.c_ubyte)]


class BITMAPINFO(ctypes.Structure):
    _fields_ = [("bmiHeader", BITMAPINFOHEADER), ("bmiColors", RGBQUAD * 1)]


def korean_chars() -> list[str]:
    chars: set[str] = set()
    for path in (ROOT / "src").glob("*.c"):
        text = path.read_text(encoding="utf-8")
        for literal in re.findall(r'L"([^"\\]*(?:\\.[^"\\]*)*)"', text):
            chars.update(c for c in literal if "\uac00" <= c <= "\ud7a3")
    return sorted(chars)


def rasterize(chars: list[str]) -> dict[str, list[int]]:
    gdi = ctypes.windll.gdi32
    dc = gdi.CreateCompatibleDC(0)
    info = BITMAPINFO(BITMAPINFOHEADER(ctypes.sizeof(BITMAPINFOHEADER), W, -H, 1, 32, 0, W * H * 4, 0, 0, 0, 0))
    bits = ctypes.c_void_p()
    bitmap = gdi.CreateDIBSection(dc, ctypes.byref(info), 0, ctypes.byref(bits), 0, 0)
    old_bitmap = gdi.SelectObject(dc, bitmap)
    font = gdi.CreateFontW(-12, 0, 0, 0, 400, 0, 0, 0, 129, 0, 0, 3, 1, "GulimChe")
    old_font = gdi.SelectObject(dc, font)
    gdi.SetTextColor(dc, 0xFFFFFF)
    gdi.SetBkColor(dc, 0)
    out: dict[str, list[int]] = {}
    pixels = (ctypes.c_uint32 * (W * H)).from_address(bits.value)
    for ch in chars:
        gdi.PatBlt(dc, 0, 0, W, H, 0x00000042)
        gdi.TextOutW(dc, 0, 0, ch, 1)
        rows = []
        for y in range(H):
            row = 0
            for x in range(W):
                if pixels[y * W + x] & 0xFFFFFF:
                    row |= 1 << (W - 1 - x)
            rows.append(row)
        out[ch] = rows
    gdi.SelectObject(dc, old_font)
    gdi.SelectObject(dc, old_bitmap)
    gdi.DeleteObject(font)
    gdi.DeleteObject(bitmap)
    gdi.DeleteDC(dc)
    return out


def write_png(path: Path, width: int, height: int, rgb: bytes) -> None:
    def chunk(name: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + name + data + struct.pack(">I", zlib.crc32(name + data) & 0xFFFFFFFF)
    scan = b"".join(b"\0" + rgb[y * width * 3:(y + 1) * width * 3] for y in range(height))
    path.parent.mkdir(parents=True, exist_ok=True)
    data = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(scan, 9)) + chunk(b"IEND", b"")
    if path.exists() and png_content(path.read_bytes()) == png_content(data): return
    path.write_bytes(data)


def png_content(data: bytes):
    try:
        pos, metadata, compressed = 8, [], bytearray()
        while pos < len(data):
            size = struct.unpack(">I", data[pos:pos + 4])[0]
            name, payload = data[pos + 4:pos + 8], data[pos + 8:pos + 8 + size]
            (compressed.extend(payload) if name == b"IDAT" else metadata.append((name, payload)))
            pos += size + 12
        return metadata, zlib.decompress(compressed)
    except (struct.error, zlib.error):
        return None


def emit(glyphs: dict[str, list[int]]) -> None:
    generated = ROOT / "src" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by tools/build_font.py. */", "static const KoGlyph KO_FONT[] = {"]
    for ch, rows in glyphs.items():
        values = ",".join(f"0x{row:03x}" for row in rows)
        lines.append(f"    {{0x{ord(ch):04x},{{{values}}}}},")
    lines += ["};", "#define KO_FONT_COUNT (sizeof(KO_FONT)/sizeof(KO_FONT[0]))", ""]
    (generated / "font_ko.inc").write_text("\n".join(lines), encoding="utf-8")

    cols, cell_w, cell_h = 16, 16, 16
    rows_n = (len(glyphs) + cols - 1) // cols
    rgb = bytearray(cols * cell_w * rows_n * cell_h * 3)
    for i, rows in enumerate(glyphs.values()):
        ox, oy = i % cols * cell_w + 2, i // cols * cell_h + 2
        for y, bits in enumerate(rows):
            for x in range(W):
                if bits & (1 << (W - 1 - x)):
                    p = ((oy + y) * cols * cell_w + ox + x) * 3
                    rgb[p:p + 3] = b"\xf2\xeb\xdd"
    write_png(ROOT / "art" / "review" / "font_ko_contact.png", cols * cell_w, rows_n * cell_h, bytes(rgb))


if __name__ == "__main__":
    emit(rasterize(korean_chars()))
